global:
  scrape_interval:     1m   # default = 1m
  scrape_timeout:      10s  # default = 10s

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'speedtest-exporter'
    scrape_interval: 15m
    scrape_timeout: 1m # running speedtest needs time to complete
    static_configs:
      - targets: ['speedtest-exporter:9798']

#  - job_name: 'docker'
#    static_configs:
#      - targets: ['localhost:9323']
