version: '3'

volumes:
  volume_grafana:
    external: true
  volume_prometheus:
    external: true

networks:
  bridge_monitoring_stack:
    name: bridge_monitoring_stack

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    networks:
      - bridge_monitoring_stack
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - volume_grafana:/var/lib/grafana/

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    networks:
      - bridge_monitoring_stack
    ports:
      - 9090:9090/tcp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./prometheus/:/etc/prometheus/
      - volume_prometheus:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/usr/share/prometheus/console_libraries'
      #- '--web.console.templates=/usr/share/prometheus/consoles'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    hostname: node_exporter
    networks:
      - bridge_monitoring_stack
    expose:
      - 9100/tcp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'

  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    hostname: speedtest-exporter
    networks:
      - bridge_monitoring_stack
    expose:
      - 9798/tcp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    networks:
      - bridge_monitoring_stack
    ports:
      - 8080:8080/tcp
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    networks:
      - bridge_monitoring_stack
    ports:
      - 6379:6379/tcp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
