apiVersion: 1

deleteDatasources:
  - name: 'datasource_prometheus'

datasources:
  - name: 'datasource_prometheus'
    type: prometheus
    url: http://prometheus:9090
    uid: 'datasource_prometheus'
    editable: true
